#define K_SEMICOLON                      1
#define K_CREATE                         2
#define K_STREAM                         3
#define IDENTIFIER                       4
#define K_OPEN_BRACKET                   5
#define K_CLOSE_BRACKET                  6
#define K_JOIN                           7
#define K_ON                             8
#define K_VIEW                           9
#define K_AS                            10
#define K_SELECT                        11
#define K_FROM                          12
#define K_OPEN_SQUARE_BRACKET           13
#define K_SLIDE                         14
#define V_LONG                          15
#define K_MS                            16
#define K_CLOSE_SQUARE_BRACKET          17
#define K_TILT                          18
#define V_DOUBLE                        19
#define K_M                             20
#define K_WAY                           21
#define V_STRING                        22
#define K_SESSION                       23
#define K_JUMPING                       24
#define K_AREA                          25
#define K_INSERT                        26
#define K_INTO                          27
#define K_VALUES                        28
#define K_COMA                          29
#define K_POINT                         30
#define K_AND                           31
#define K_OR                            32
#define K_EQUAL                         33
#define K_GREATER_THAN                  34
#define K_GRATER_THAN_EQUAL             35
#define K_LESSER_THAN                   36
#define K_LESSER_THAN_EQUAL             37
#define K_NOT_EQUAL                     38
#define K_MAX                           39
#define K_MIN                           40
#define K_DOUBLE                        41
#define K_INTEGER                       42
#define K_STRING                        43
#define K_BLOB                          44
#define K_GEOMETRY                      45
